version: '3.8'

services:
  web:
    build: .
    platform: linux/arm64
    working_dir: /app
    command: sh entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/django_db
    depends_on:
      - db

  db:
    image: arm64v8/postgres:15
    platform: linux/arm64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
